name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master  # Change to the appropriate branch if needed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '20'  # Ensure using Node.js 20

      # Setup a specific Ruby version (e.g., 3.1.6) that is compatible
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.6 # Specify an exact version of Ruby

      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
          node-version: '20'  # Ensure using Node.js 20

      - name: Install Dependencies
        run: |
          gem install bundler -v 2.3.26
          bundle install --jobs 4 --retry 3 --path vendor/bundle

      - name: Build and Deploy to GitHub Pages
        uses: jeffreytse/jekyll-deploy-action@v0.5.1
        with:
          provider: 'github'         # Default is github
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub Personal Access Token (PAT)
          branch: 'gh-pages'         # Branch to deploy to
          jekyll_src: './'           # Directory to build from
          jekyll_cfg: '_config.yml'  # Jekyll configuration file
          bundler_ver: '2.3.26'      # Specify the Bundler version according to Gemfile.lock
          pre_build_commands: 'bundle exec jekyll build' # Build the site before deploying

      - name: Cleanup
        run: |
          bundle clean --force
          rm -rf vendor
