name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [RUN_WORKFLOW_DISPATCH]

permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  import_data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      
      - name: Clean Directory
        run: |
          for file in assets/images/*
          do
              case $file in
                  assets/images/88x88.png | \
                  assets/images/bio-photo_202424.jpg | \
                  assets/images/bio-photo.jpg | \
                  assets/images/bio-photo.png | \
                  assets/images/effective-hazard-prevention-1.png | \
                  assets/images/favicon.png | \
                  *.svg)
                      continue
                      ;;
                  *)
                      rm -rf "$file"
                      ;;  
              esac
          done
          rm -rf _posts/*
          rm -rf _projects/*
      
      - uses: actions/setup-node@v3
        with:
          node-version: "17"

      - run: npm install

      - run: node _scripts/notion-api.js
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.BLOG_DB_ID }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "[배포] Notion 변경 사항 저장"
          branch: master
          commit_user_name: importer-bot 🤖
          commit_user_email: actions@github.com
          commit_author: importer-bot 🤖 <actions@github.com>

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: import_data
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure latest master branch
        run: |
          git checkout master
          git pull origin master --rebase

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v4
        with:
          path: |
            .asdf/**
            vendor/bundle
          key: ${{ runner.os }}-cache-${{ hashFiles('**/cache.key') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@master
        with:
          provider: 'github'         # Default is github
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          ssh_private_key: ''        # It's your SSH private key (SSH approach)
          repository: ''             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          ruby_ver: ''               # Default is 3.2.0 version
          bundler_ver: ''            # Default is compatible bundler version (~>2.5.0)
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
          pre_build_commands: ''     # Installing additional dependencies (Arch Linux)
